#!/bin/bash

echo "enter a phrase"
read phrase

# counting words
word=$(echo -n "$phrase" | wc -w)
# counting number of white spaces
space=$(expr length "$phrase" - length `echo "$phrase" | sed "s/ //g"`)

echo "Number of words= $word"
echo "Number of White Spaces=$space"
